import { Button } from '@chakra-ui/react'
import Head from 'next/head'
import Image from 'next/image'
import Navbar from '../Components/Navbar'
import styles from '../styles/Home.module.css'

export default function Home({git,project}) {
  
  console.log(project)
  return (
    <div className={styles.container}>
      <Head>
      
      
      <title>Home Page</title>
            <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
          </Head>
         <Navbar img={git.avatar_url}  />
  
       {/* <img src={git.avatar_url} style={{width:"200px",borderRadius:"50%"}} alt={git.name} /> */}
      <div>{git.id}</div>
        <div>{git.name}</div>
          <div>@{git.login}</div>
      <div>{git.bio}</div>
     
      <div style={{display:"flex" ,gap:"5px"}}>
        <Button ><a href={git.blog}>Resume</a></Button>
        <Button><a href={git.html_url}>Follow</a></Button>
      </div>
      <div><b>TechStack:-</b>{git.bio}</div>
     <div>
        <div><b>Experience Education</b></div>
      <div>
      <div>{git.company}(Full Time)</div>
  <div>Masters in Tourism  and Travel Management</div>
  <div>Following:-{git.following}</div>
  <div>Followers:-{git.followers}</div>
      </div>
     </div>


<div>
 <h1>Projects</h1>


</div>

{project.map((e) => 


        <div key={e.id} style={{border:"1px solid" ,display:"flex",gap:"27px" ,padding:"10px"}}>
          <div>
            <a href={e.html_url}><b>{e.name} --Click here</b></a>
            <div>{e.description?e.description:""}</div>
            <div>
              
          <div>Stars Count:- {e.stargazers_count}</div>
          <div>ForkCount:- {e.forks}</div>
   
            </div>

          </div>
          

          <div>language:- {e.language}</div>
        </div>
      )}

     

    </div>
  )
}
export async function getStaticProps(){
  let res =await fetch(`https://api.github.com/users/ankitraju123`)
  let data=await res.json()
  let res1=await fetch(`https://api.github.com/search/repositories?q=user:ankitraju123+fork:true&sort=updated&per_page=10&type=Repositories`)
  let data1=await res1.json()

  return {
    props:{
      git:data,
      project:data1.items
    }
  }
 }
// export async function getStaticProps(){
//   let res =await fetch(`
//   https://api.github.com/search/repositories?q=user:mojombo+fork:true&sort=updated&per_page=10&type=Repositories`)
//   let data=await res.json()

//   return {
//     props:{
//       github:data
//     }
//   }
// }